# Resmi Node.js imajını kullan
FROM node:22

# Çalışma dizinini ayarla
WORKDIR /app

# Paket dosyalarını kopyala ve bağımlılıkları yükle
COPY package*.json ./
RUN npm install

# Tüm dosyaları kopyala
COPY . .

# Vite'i başlat
CMD ["npm", "run", "dev"]