FROM python:3.11
WORKDIR /app
RUN apt-get update && apt-get install -y docker.io
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]